# Numpy (Numerical Python)

### 1. 넘파이 설치 확인

In [1]:
import numpy as np
print(np.__version__)

2.0.1


### 2. 넘파이 배열 (ndarray)생성과 속성 확인

In [2]:
a1= np.array([1, 2, 3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
a2= np.array((1, 2, 3))
print(a2, type(a1), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [3]:
a3 = np.array([[1, 2, 3], [4, 5, 6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [4]:
a4 = np.array([1, 2, 3], dtype=float)
print(a4, type(a4), a4.dtype, a4.ndim, a4.shape, a4.size)

[1. 2. 3.] <class 'numpy.ndarray'> float64 1 (3,) 3


In [5]:
a6 = np.array([1, 4, 5, '8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

['1' '4' '5' '8']
<class 'numpy.ndarray'> <U21 1 (4,) 4


In [6]:
a6 = np.array([1, 4, 5, '8'], int)
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

[1 4 5 8]
<class 'numpy.ndarray'> int64 1 (4,) 4


In [ ]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]
# np.array(test_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3.인덱싱 (indexing)

In [8]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d[0],d[1],d[2],d[-1],d[-2])

1 2 3 9 8


In [9]:
d2=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0][0]) # 배열명[행][열] 형태
print(d2[0, 0]) # 배열명[행, 열] 형태
print(d2[1, 1])
print(d2[1, -1])

1
1
7
10


In [10]:
d3=np.arange(12).reshape(2,2,3)
print(d3[0][0][0]) # 배열명[면][행][열] 형태
print(d3[0, 0, 0]) # 배열명[면,행,열] 형태
print(d3[1, 1, 2])
print(d3[-1, -1, -1])
d[3] = 100
print(d)
d2[1, 1] = 100
print(d2)
d3[1, 1, 1] = 1000
print(d3)

0
0
11
11
[  1   2   3 100   5   6   7   8   9]
[[  1   2   3   4   5]
 [  6 100   8   9  10]]
[[[   0    1    2]
  [   3    4    5]]

 [[   6    7    8]
  [   9 1000   11]]]


In [11]:
d3[0] = 50
print(d3)

[[[  50   50   50]
  [  50   50   50]]

 [[   6    7    8]
  [   9 1000   11]]]


In [12]:
d3[1,0] = 30
print(d3)

[[[  50   50   50]
  [  50   50   50]]

 [[  30   30   30]
  [   9 1000   11]]]


### 4. 슬라이싱 (Slicing)

In [13]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [14]:
d2 = np.arange(1,11).reshape(2,-1)
print(d2[0]) # 0행만 슬라이싱
print(d2[0,:]) # 0행의 전체 열 슬라이싱
print(d2[:, :-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d2[::2,::2]) # 2행 2열 간격으로 전체 행과 열 슬라이싱

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [15]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [16]:
d2 = np.arange(1,11).reshape(2,-1)
print(d2)
print(d2[::2, ::3])
d2[::2, ::3] = 30
print(d2)
d2[:, :] = -1
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### 5.불 인덱싱(Boolean indexing)

In [17]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data[data >3])
print(data > 3)
cond = [False, True, True, False, False, True]
print(data[cond])
# 2보다 크고 6보다 작은 요소만 추출
print(data[(data > 3) & (data < 6)])
# 짝수만 출력
print(data[data % 2 == 0])
# 평균보다 작은 값만 추출
print(data[data < data.mean()])

[4 6 7]
[ True  True  True False False False]
[6 7 0]
[4]
[4 6 2 0]
[3 2 0]


### 6. 팬시 인덱싱 (Fancy indexing)

In [18]:
f = np.array([4, 6, 7, 3, 2])
indexes = np.array([1, 2, 0, 2, 2, 2])
print(f)
print(indexes)
print(f[indexes])
f2 = np.array([[1, 4], [9, 16]])
x = np.array([0, 1, 1, 1, 0, 0])
y = np.array([0, 0, 0, 1, 1, 1])
print(f2)
print(x)
print(y)
print(f2[x,y])

[4 6 7 3 2]
[1 2 0 2 2 2]
[6 7 4 7 7 7]
[[ 1  4]
 [ 9 16]]
[0 1 1 1 0 0]
[0 0 0 1 1 1]
[ 1  9  9 16  4  4]


### 7. 넘파이 배열의 정렬

In [19]:
# 기본 정렬 : sort함수
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6,])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])
numbers.sort()
print(numbers)

# 2차원 배열의 정렬
arr2d=np.array([[5, 6, 7, 8],[4, 3, 2, 1],[10, 9, 12, 11]])
print(arr2d)
print(np.sort(arr2d))
print(np.sort(arr2d, axis=1))
print(np.sort(arr2d, axis=0))

# argsort 함수
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

# [연습문제] 이름을 성적 순서로 출력하기
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])

sort_score = np.argsort(scores)[::-1]
print(sort_score)
print(names[sort_score])

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]
[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]
[5 0 4 6 7 8 3 1 2]
[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


### 8. 넘파이 배열의 사칙연산

In [20]:
# 브로드캐스팅 (broadcasting)
# - 모양(shape)이 다른 배열들 간에도 산술 연산이 가능하게 하는 기능 (
x = np.arange(1, 7).reshape(2, 3)
print(x)
print(x + x)
print(x + 2)
y = np.array([10, 20, 30])
print(x + y)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
[[11 22 33]
 [14 25 36]]


### 9. 넘파이 함수의 활용

In [21]:
arr=np.array([[5, 6, 7, 8],[4, 3, 2, 1],[10, 9, 12, 11]])
print(arr.sum(axis = 1))
print(arr.mean(axis = None))
print(arr.max(axis =None))
print(arr.min(axis = None))
print(arr.argmax(axis = None))
print(arr.argmin(axis = None))
print(arr.all(axis = None))
print(np.all(arr > 3,axis = None))


# 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data)))

# 두 배열이 완전히 동일한지 확인
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(np.all(arr1 == arr2))

[26 10 42]
6.5
12
1
10
7
True
False
True
True
